### ISSUE TITLE
Move repo to tlaplus foundation org

### ISSUE THREAD

**Issue by lemmy** [tlaplus-community/tlaplus-standard#4]
It might be a good idea to have a tlaplus-standard repository within the [TLA+ Foundation organization](https://github.com/tlaplus/) on GitHub.

**Comment by lemmy** [comment]
Ping

**Comment by ahelwer** [comment]
Oops didn't have watch set up here. Yeah we could do that, as long as I keep write access to it.

**Comment by lemmy** [comment]
I believe this is the default when a repo is moved.

**Comment by ahelwer** [comment]
@lemmy it does not appear this was the case (I cannot close this issue on my own for example)

**Comment by lemmy** [comment]
Try again
